describe('neopilot.log', function()
  it('should be able to call log functions without error', function()
    local log = require('neopilot.log')
    assert.does_not.error(function()
      log.info('test message')
      log.warn('test message')
      log.error('test message')
    end)
  end)
end)
